In [1]:
import os

import numpy as np
import pandas as pd

from getpass import getpass
from mysql.connector import connect, Error

In [2]:
data_dir = os.path.join("..", "Datasets", "db")
customer_t = pd.read_csv(os.path.join(data_dir, "Customers.csv"))
location_t = pd.read_csv(os.path.join(data_dir, "Locations.csv"))
order_detail_t = pd.read_csv(os.path.join(data_dir, "Order_Details.csv"))
order_t = pd.read_csv(os.path.join(data_dir, "Orders.csv"))
product_t = pd.read_csv(os.path.join(data_dir, "Products.csv"))

In [3]:
product_t[product_t["product_name"].duplicated()]

,product_code,product_name,category,sub_category,product_id
259,OFF-PA-10000474,Easy-staple paper,Office Supplies,Paper,259
409,OFF-EN-10001415,Staple envelope,Office Supplies,Envelopes,409
466,OFF-FA-10002815,Staples,Office Supplies,Fasteners,466
486,OFF-SU-10001935,Staple remover,Office Supplies,Supplies,486
554,OFF-FA-10003112,Staples,Office Supplies,Fasteners,554
711,OFF-EN-10001099,Staple envelope,Office Supplies,Envelopes,711
745,FUR-FU-10001940,Staple-based wall hangings,Furniture,Furnishings,745
793,OFF-AR-10004790,Staples in misc. colors,Office Supplies,Art,793
817,OFF-PA-10000349,Easy-staple paper,Office Supplies,Paper,817
819,OFF-PA-10003127,Easy-staple paper,Office Supplies,Paper,819
835,OFF-FA-10003495,Staples,Office Supplies,Fasteners,835
843,OFF-EN-10001539,Staple envelope,Office Supplies,Envelopes,843
854,OFF-FA-10000735,Staples,Office Supplies,Fasteners,854
892,OFF-PA-10001685,Easy-staple paper,Office Supplies,Paper,892
907,OFF-AR-10002280,Staples in misc. colors,Office Supplies,Art,907
986,FUR-TA-10001039,KI Adjustable-Height Table,Furniture,Tables,986
999,OFF-BI-10004364,Storex Dura Pro Binders,Office Supplies,Binders,999
1023,OFF-FA-10003021,Staples,Office Supplies,Fasteners,1023
1044,FUR-FU-10003981,Eldon Wave Desk Accessories,Furniture,Furnishings,1044
1049,OFF-EN-10003134,Staple envelope,Office Supplies,Envelopes,1049
1109,OFF-FA-10001843,Staples,Office Supplies,Fasteners,1109
1125,OFF-PA-10004947,Easy-staple paper,Office Supplies,Paper,1125
1169,OFF-AR-10003631,Staples in misc. colors,Office Supplies,Art,1169
1180,OFF-EN-10002621,Staple envelope,Office Supplies,Envelopes,1180
1200,OFF-ST-10002562,Staple magnet,Office Supplies,Storage,1200
1224,OFF-EN-10000781,"#10- 4 1/8"" x 9 1/2"" Recycled Envelopes",Office Supplies,Envelopes,1224
1238,OFF-FA-10002975,Staples,Office Supplies,Fasteners,1238
1308,OFF-AP-10002222,Staple holder,Office Supplies,Appliances,1308
1340,OFF-AR-10003087,Staples in misc. colors,Office Supplies,Art,1340
1343,OFF-FA-10001229,Staples,Office Supplies,Fasteners,1343
1382,OFF-BI-10000829,Avery Non-Stick Binders,Office Supplies,Binders,1382
1463,OFF-SU-10000946,Staple remover,Office Supplies,Supplies,1463
1470,OFF-EN-10003286,Staple envelope,Office Supplies,Envelopes,1470
1524,OFF-EN-10004773,Staple envelope,Office Supplies,Envelopes,1524
1577,OFF-AR-10004062,Staples in misc. colors,Office Supplies,Art,1577
1633,OFF-EN-10001028,Staple envelope,Office Supplies,Envelopes,1633
1649,OFF-AR-10002766,Prang Drawing Pencil Set,Office Supplies,Art,1649
1671,OFF-AP-10001366,Staple holder,Office Supplies,Appliances,1671
1681,OFF-PA-10000565,Easy-staple paper,Office Supplies,Paper,1681
1739,OFF-FA-10003485,Staples,Office Supplies,Fasteners,1739
1741,OFF-PA-10002764,Easy-staple paper,Office Supplies,Paper,1741
1789,OFF-EN-10002592,"Peel & Seel Recycled Catalog Envelopes, Brown",Office Supplies,Envelopes,1789
1850,TEC-MA-10001856,Okidata C610n Printer,Technology,Machines,1850
1852,OFF-AR-10004707,Staples in misc. colors,Office Supplies,Art,1852

In [4]:
product_t.nunique()

product_code    1862
product_name    1850
category           3
sub_category      17
product_id      1894
dtype: int64

In [5]:
order_t

            order_id  order_date   ship_date       ship_mode customer_id
0     CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1     CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
2     US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
3     CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710
4     CA-2017-114412  2017-04-15  2017-04-20  Standard Class    AA-10480
...              ...         ...         ...             ...         ...
5004  CA-2016-125794  2016-09-29  2016-10-03  Standard Class    ML-17410
5005  CA-2017-163629  2017-11-17  2017-11-21  Standard Class    RA-19885
5006  CA-2014-110422  2014-01-21  2014-01-23    Second Class    TB-21400
5007  CA-2017-121258  2017-02-26  2017-03-03  Standard Class    DB-13060
5008  CA-2017-119914  2017-05-04  2017-05-09    Second Class    CC-12220

[5009 rows x 5 columns]

In [6]:
product_t['product_name'].nunique()

1850

In [8]:
customer_t

    customer_id      customer_name      segment
0      CG-12520        Claire Gute     Consumer
1      DV-13045    Darrin Van Huff    Corporate
2      SO-20335     Sean O'Donnell     Consumer
3      BH-11710    Brosina Hoffman     Consumer
4      AA-10480       Andrew Allen     Consumer
..          ...                ...          ...
788    CJ-11875       Carl Jackson    Corporate
789    RS-19870         Roy Skaria  Home Office
790    SC-20845         Sung Chung     Consumer
791    RE-19405    Ricardo Emerson     Consumer
792    SM-20905  Susan MacKendrick     Consumer

[793 rows x 3 columns]

In [7]:
## Data Preparation
# customer_t = customer_t.rename(columns={"customer_id": "customer_code"})
# customer_t["customer_id"] = customer_t.index
customer_t = customer_t[["customer_id", "customer_name", "segment", "email", "password", "username"]]

product_t = product_t[["product_id", "product_name", "product_code", "category", "sub_category", "product_price"]]
product_t["product_id"] = product_t["product_id"].astype("str")

location_t = location_t[["location_id", "country", "city", "state", "postal_code", "region"]]
location_t["location_id"] = location_t["location_id"].astype("str")
location_t["postal_code"] = location_t["postal_code"].astype("str")

# order_t = order_t.rename(columns={"order_id": "order_code"})
# order_t['order_id'] = order_t.index
order_t = order_t[["order_id", "order_date", "ship_date", "ship_mode", "customer_id"]]

order_detail_t = order_detail_t[["order_detail_id", "order_id", "product_id", "location_id", "sales", "quantity", 
                                     "discount", "profit"]]
order_detail_t["order_detail_id"] = order_detail_t["order_detail_id"].astype("str")
order_detail_t["product_id"] = order_detail_t["product_id"].astype("str")
order_detail_t["location_id"] = order_detail_t["location_id"].astype("str")
# customer_t["customer_id"] = customer_t["customer_id"].astype("str")
# order_t["order_id"] = order_t["order_id"].astype("str")
order_detail_t["sales"] = order_detail_t["sales"].astype("str")
order_detail_t["quantity"] = order_detail_t["quantity"].astype("str")
order_detail_t["discount"] = order_detail_t["discount"].astype("str")
order_detail_t["profit"] = order_detail_t["profit"].astype("str")

KeyError: "['email', 'password', 'username'] not in index"

### `Connecting to MySQL`

In [ ]:
username = "root"
password = "123m"

In [ ]:
try:
    conn = connect(
        host="localhost",
        user=username,
        password=password,
        port="3306"
    ) 
    print(conn)
except Error as e:
    print(e)

In [ ]:
curr = conn.cursor()

### `Setup DB`

In [15]:
db_name = "sales_db"

In [16]:
sql_create_db = "CREATE DATABASE IF NOT EXISTS {};".format(db_name)

curr.execute(sql_create_db)

In [17]:
# sql_use_db = "USE sales_db;"

# curr.execute(sql_use_db)

In [18]:
# RE-CONNECTION: specific to database only

try:
    conn = connect(
        host="localhost",
        user=username,
        password=password,
        database=db_name
    ) 
    print(conn)
except Error as e:
    print(e)

<mysql.connector.connection_cext.CMySQLConnection object at 0x7efbf20459d0>

In [19]:
curr = conn.cursor()

### `Table Creation`

In [20]:
order_t

            order_id  order_date   ship_date       ship_mode customer_id
0     CA-2016-152156  2016-11-08  2016-11-11    Second Class    CG-12520
1     CA-2016-138688  2016-06-12  2016-06-16    Second Class    DV-13045
2     US-2015-108966  2015-10-11  2015-10-18  Standard Class    SO-20335
3     CA-2014-115812  2014-06-09  2014-06-14  Standard Class    BH-11710
4     CA-2017-114412  2017-04-15  2017-04-20  Standard Class    AA-10480
...              ...         ...         ...             ...         ...
5004  CA-2016-125794  2016-09-29  2016-10-03  Standard Class    ML-17410
5005  CA-2017-163629  2017-11-17  2017-11-21  Standard Class    RA-19885
5006  CA-2014-110422  2014-01-21  2014-01-23    Second Class    TB-21400
5007  CA-2017-121258  2017-02-26  2017-03-03  Standard Class    DB-13060
5008  CA-2017-119914  2017-05-04  2017-05-09    Second Class    CC-12220

[5009 rows x 5 columns]

In [21]:
# customers table
sql_create_table_customers = """
    CREATE TABLE IF NOT EXISTS Customers(
        row_id INT AUTO_INCREMENT,
        customer_id varchar(75) PRIMARY KEY,
        customer_name varchar(250) NOT NULL,
        segment varchar(100) NOT NULL,
        email varchar(250),
        password varchar(250),
        username varchar(200),
        INDEX(row_id)
    );
"""

# products table
sql_create_table_products = """
    CREATE TABLE IF NOT EXISTS Products(
        row_id INT unsigned PRIMARY KEY,
        product_name varchar(300) NOT NULL,
        product_code varchar(300) NOT NULL,
        category varchar(100),
        sub_category varchar(100),
        product_price float
    );
"""

# locations table
sql_create_table_locations = """
    CREATE TABLE IF NOT EXISTS Locations(
        row_id INT unsigned PRIMARY KEY,
        country varchar(150) NOT NULL,
        city varchar(150) NOT NULL,
        state varchar(150),
        postal_code varchar(50),
        region varchar(50)
    );
"""

# orders table
sql_create_table_orders = """
    CREATE TABLE IF NOT EXISTS Orders(
        row_id int AUTO_INCREMENT,
        order_id varchar(75) PRIMARY KEY,
        order_date date NOT NULL,
        ship_date date,
        ship_mode varchar(50),
        customer varchar(75),
        INDEX(row_id), 
        FOREIGN KEY (customer) REFERENCES Customers(customer_id)
    );
"""

# order details table
sql_create_table_order_details = """
    CREATE TABLE IF NOT EXISTS OrderDetails(
        row_id int unsigned PRIMARY KEY,
        order_id varchar(75) NOT NULL,
        product_bought int unsigned NOT NULL,
        location_bought int unsigned NOT NULL,
        sales float NOT NULL,
        quantity int NOT NULL,
        discount float,
        profit float,
        FOREIGN KEY (order_id) REFERENCES Orders(order_id),
        FOREIGN KEY (product_bought) REFERENCES Products(row_id),
        FOREIGN KEY (location_bought) REFERENCES Locations(row_id)
    );
"""

In [22]:
curr.execute(sql_create_table_customers)
curr.execute(sql_create_table_products)
curr.execute(sql_create_table_locations)
curr.execute(sql_create_table_orders)
curr.execute(sql_create_table_order_details)

### `Data Insertion`

In [23]:
# customers insertion
sql_insert_customers = """
    INSERT INTO Customers
        (customer_id, customer_name, segment, email, password, username)
        VALUES (%s, %s, %s, %s, %s, %s)
"""
curr.executemany(sql_insert_customers, customer_t.values.tolist())


# products insertion
sql_insert_products = """
    INSERT INTO Products
        (row_id, product_name, product_code, category, sub_category, product_price)
        VALUES (%s, %s, %s, %s, %s, %s)
        
"""
curr.executemany(sql_insert_products, product_t.values.tolist())


# locations insertion
sql_insert_locations = """
    INSERT INTO Locations
        (row_id, country, city, state, postal_code, region)
        VALUES (%s, %s, %s, %s, %s, %s)
        
"""
curr.executemany(sql_insert_locations, location_t.values.tolist())

# orders insertion
sql_insert_orders = """
    INSERT INTO Orders
        (order_id, order_date, ship_date, ship_mode, customer)
        VALUES (%s, %s, %s, %s, %s)
"""
curr.executemany(sql_insert_orders, order_t.values.tolist())

# order details insertion
sql_insert_order_details = """
    INSERT INTO OrderDetails
        (row_id, order_id, product_bought, location_bought, sales, quantity, discount, profit)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        
"""
curr.executemany(sql_insert_order_details, order_detail_t.values.tolist())

In [24]:
conn.commit()

In [37]:
# try:
#     conn = connect(
#         host="localhost",
#         user=username,
#         password=password,
#         database=db_name
#     ) 
#     print(conn)
# except Error as e:
#     print(e)

# curr = conn.cursor()

# sql_create_table_orders2 = """
#     CREATE TABLE IF NOT EXISTS Orders10(
#         row_id int AUTO_INCREMENT,
#         order_id varchar(75) PRIMARY KEY,
#         order_date date NOT NULL,
#         ship_date date,
#         ship_mode varchar(50),
#         customer varchar(75),
#         INDEX(row_id), 
#         FOREIGN KEY (customer) REFERENCES Customers(customer_id)
#     );
# """
# curr.execute(sql_create_table_orders2)
# conn.commit()

In [36]:
# try:
#     conn = connect(
#         host="localhost",
#         user=username,
#         password=password,
#         database=db_name
#     ) 
#     print(conn)
# except Error as e:
#     print(e)

# curr = conn.cursor()

# sql_insert_orders2 = """
#     INSERT INTO Orders10
#         (order_id, order_date, ship_date, ship_mode, customer)
#         VALUES (%s, %s, %s, %s, %s)
# """
# curr.executemany(sql_insert_orders2, order_t.values.tolist())


# conn.commit()

<mysql.connector.connection_cext.CMySQLConnection object at 0x7f86b0a98970>